---
title: "Developing Data Products - Week 3 Project"
author: "David Erhart"
date: "12/6/2021"
output: 
        slidy_presentation:
                css: my.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(MASS)
```

## 2D Bivariate Normal Contour Histogram (with correlation)

```{r, echo = FALSE, cache = TRUE}
N <- 2000 # Number of random samples
set.seed(123)
# Target parameters for univariate normal distributions
rho <- -0.6 # correlation
mu1 <- 1; s1 <- 2
mu2 <- 3; s2 <- 8

# Parameters for bivariate normal distribution
mu <- c(mu1,mu2) # Means
sigma <- matrix(c(s1^2, s1*s2*rho, s1*s2*rho, s2^2), 2) # Covariance matrix

bivariate_normal <-as.data.frame( mvrnorm(N, mu = mu, Sigma = sigma )) # from MASS package
colnames(bivariate_normal) <- c("bvn_X1","bvn_X2")
```

<div class = 'center'>
```{r, echo = FALSE}
fig <- plot_ly(bivariate_normal, x = ~bvn_X1,
               y = ~bvn_X2,
               width = 750, height = 750)

fig <- fig %>%
  add_trace(type='histogram2dcontour')

yaxis <- list(
  title = 'Normal Variable 2',
  automargin = TRUE,
  titlefont = list(size=20)
)

xaxis <- list(
  title = 'Normal Variable 1',
  automargin = TRUE,
  titlefont = list(size=20)
)

fig <- fig %>% layout(autosize = F, xaxis = xaxis, yaxis = yaxis)

fig
```
</div>